Module 1 Capstone Project
Fene-87/Module-1-Capstone pull request #1
Opened 2023-01-04 15:32 UTC by Fene-87

This is a project for an art fair summit

2023-01-04 19:02 UTC, huseyinbiyik requested changes
Hi @Fene-87,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Very good-looking implementation for the given design. 👌
- Commit messages are meaningful and have imperative tense 👌
- Linter set up well and checks pass 🟢

## Required Changes ♻️
- Your presentation video is good but kindly show a piece of code you are proud of. You are proud of the accessibility and simplicity of your code but don't show any of them :) As a suggestion, that would be fantastic if you can show the more+less function code in the speaker section.
- Please make sure you have no git conflict when submitting your Pull Request.
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 19:02 UTC, huseyinbiyik commented on README.md
[OPTIONAL] You can add your Loom video link here instead of the PR description. The visitors to this repository will understand your project goal better. Also, you will notice some HRs watch your presentation.👨‍💼

2023-01-04 19:02 UTC, huseyinbiyik commented on about.html
> +        </div>
- Please fix the footer, the background needs to be black on the desktop version. 👨‍🎨 Kindly stick to the design as much as possible. 
<img width="957" alt="Screenshot 2023-01-04 at 9 13 39 PM" src="https://user-images.githubusercontent.com/25887253/210622623-8f15eff8-eaf8-476e-a1da-a85f4f7e5d54.png">
<img width="1440" alt="Screenshot 2023-01-04 at 9 14 02 PM" src="https://user-images.githubusercontent.com/25887253/210622642-f066f645-ad6f-4848-b834-d49865d94637.png">

2023-01-04 19:02 UTC, huseyinbiyik commented on about.html
> +        <h1 class="about-header">GLOBAL INTERNATIONAL ART FAIR 2023</h1>
- There is an issue with the Cocogoose font which occurs so often. It is mostly with numbers. Kindly try to fix it using other sources for the font family, if you can't find it, remove the numbers. Check how it looks like on Live Demo.
![Screen Recording 2023-01-04 at 9 30 33 PM](https://user-images.githubusercontent.com/25887253/210625585-cb4eac30-a692-4b6b-a177-a99cad77fbb3.gif)

2023-01-04 19:02 UTC, huseyinbiyik commented on index.html
> +                />
Please make sure each `<img>` element on the repo has an alt attribute. This is crucial for the accessibility and SEO of your web site.

2023-01-04 19:02 UTC, huseyinbiyik commented on app.js
> +});
Good job but let's make your code DRYer. You have repeating code pieces obviously. Also, speaker images need to be inside speakerInfo array. Check this [link](https://github.com/huseyinbiyik/world-tomato-forum/blob/main/script.js) code to get inspired.

2023-01-05 10:08 UTC, m05e5 requested changes
Hi @Fene-87 , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Please check the comments below 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 10:08 UTC, m05e5 commented on about.html
> +            />
- [ ]  Hi please as mentioned by the previous reviewer, please make sure each <img> element on the repo has an alt attribute. This is crucial for the accessibility and SEO of your webApp. Also, ill recommends giving your Images a proper alternative text (`alt`).

2023-01-05 10:52 UTC, Fene-87 commented
I have implemented all required changes.

2023-01-05 11:01 UTC, fobadara approved these changes
Hi @Fene-87, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Linters are passing

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 11:19 UTC, merged